name: Publish Docker for WEB

on:
  push:
    branches:
      - 'main'
  pull_request_target:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Branch name
        run: echo running on branch ${{ steps.extract_branch.outputs.branch }}

      - name: Validate Build Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.event_name == 'pull_request'
        with:
          context: ./web
          file: ./deploy/web.dockerfile
          push: false

      - name: Build and push Docker image PROD
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/main'
        with:
          context: ./web
          file: ./deploy/web.dockerfile
          push: true
          tags: |
            "devcst/compliaiweb"
            "devcst/compliaiweb:${{github.run_number}}"